### ISSUE TITLE
quote get panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mmbros** [mmbros/quote#1]
`quote get` with real ISINs in the `/home/user/.quote.yaml` config file.
Error returned:

	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x743592]

	goroutine 36 [running]:
	github.com/mmbros/quote/internal/quote.Get.func2(0x9e8ea0, 0xc000068700, 0x2, 0x9df640, 0xc0001e0160, 0x0, 0x0)
		/home/mau/Code/prj/quote/internal/quote/quote.go:215 +0x132
	github.com/mmbros/quote/pkg/taskengine.(*Engine).Execute.func3(0xc0001e0280, 0x2, 0xc0000263c0)
		/home/mau/Code/prj/quote/pkg/taskengine/engine.go:287 +0x7a
	created by github.com/mmbros/quote/pkg/taskengine.(*Engine).Execute
		/home/mau/Code/prj/quote/pkg/taskengine/engine.go:277 +0x265
	exit status 2

**Comment by mmbros** [comment]
The panic error message is not very clear...
The problem seems caused in the `internal/quote/quote.go` file.
In the `Get` function the `resultGetQuote.ErrMsg` is setted to `err.Error()` without checking that `err != nil`.
